export const themes = {
  default: {
    primaryColor: '#FFFFFF',
    bgColor: '#EEFOF2',
    primaryHeader: '#F7F9FC',
    hoverColor: '#E8FIFD',
    buttonColor: '#1570EF',
    headerFontColor: '#383E49',
    hoverFontColor: '#1570EF',
    primaryFontColor: '#5D6679',
    primaryIconColor: '#5D6679',
    cardHeader: "#F7F9FC",
  },
  lavendar:{
    primaryColor: '#FFFFFF',
    bgColor: '#F2F2F7',
    primaryHeader: '#372B58',
    hoverColor: '#AEA5D2', 
    buttonColor: '#8B79DD ',
    tableHeader: '#E8E9F8 ',
    headerFontColor: '#AEA5D2',
    hoverFontColor: '#FFFFFF',
    primaryFontColor: '#28282B',
    primaryIconColor: '#AEA5D2',
    cardHeader: "#ECEDF8"
  },
  ocean: {
    primaryColor: '#FFFFFF',
    bgColor: '#F0F2F7',
    primaryHeader: '#051135',
    hoverColor: '#307BF6',
    buttonColor: '#307BF6',
    headerFontColor: '#B9C3CF',
    hoverFontColor: '#FFFFFF', 
    primaryFontColor: '#2B2D40',
    primaryIconColor: '#B9C3CF ',
    cardHeader: "#E6EDF9",
  },
  grassfield: {
    primaryColor: '#E5F0EF',
    bgColor: '#90BAC8',
    primaryHeader: '#1B3C43',
    hoverColor: '#3C616A',
    buttonColor: '#3C616A   ',
    headerFontColor: '#EBF8FB',
    hoverFontColor: '#FFFFFF', 
    primaryFontColor: '#343534',
    primaryIconColor: '#EBF8FB ',
    cardHeader: "#D4E3E2",
  },
  pastelgreen: {
    primaryColor: '#E5F0EF',
    bgColor: '#F6FAF9 ',
    primaryHeader: '#1B3C43',
    hoverColor: '#3C616A',
    buttonColor: '#3C616A   ',
    headerFontColor: '#EBF8FB',
    hoverFontColor: '#FFFFFF', 
    primaryFontColor: '#343534',
    primaryIconColor: '#EBF8FB ',
    cardHeader: "#D4E3E2",
  },
};
